### ISSUE TITLE
Programming with the New Alert Text

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-noaa-poly#1]
In programs for each of the alert nodes it asks for numbers   Like alerttext = 10.   Can you provide a mapping of the NOAA alert nodes and the numbers.   That way I know how to set the program.

Let me know and I can move this to UDI forum if you prefer.

**Comment by bpaauwe** [comment]
Jeff,  I believe the ISY has to be rebooted before it will display the text instead of the numbers in the programming interface. Like the admin console, it only reads that data when it first starts up.

The mappings are all in the NLS file https://github.com/bpaauwe/udi-noaa-poly/blob/master/profile/nls/en_us.txt

**Comment by macjeff** [comment]
I rebooted already but since no alerts they are all blank.   Maybe you could put NONE in those fields just so they have data?  Otherwise thanks for the mappings   That helps.
